const fs = require('fs');
const dayjs = require('dayjs');

async function updateReadmeWith(joke, gifUrl) {
  const date = dayjs().format('YYYY-MM-DD');
  const content = `# Dev Joke Bot — Daily Giggle (${date})\n\n` +
    `> ${joke.replace(/` + "`" + `/g, "\\`")}\n\n` +
    (gifUrl ? `![meme](${gifUrl})\n\n` : '') +
    `---\n*Auto-generated by the Dev Joke Bot. Remember: laughter is the second-best medicine.*\n`;

  fs.writeFileSync('README.md', content, 'utf8');
  console.log('README.md updated locally');
}

module.exports = { updateReadmeWith };
